GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title",
  "author": "Some Author",
  "URL": "URL to blog",
  "likes": 10
}

