[build]
  command = "pnpm buid"
  publish = "build"
  functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/blogs"
  status = 200