GET http://localhost:3001/api/data

###
GET http://localhost:3001/api/data/63946077b2c77e16eba069e1

###
GET http://localhost:3001/api/data/1

###
POST http://localhost:3001/api/data
Content-Type: application/json

{
  "content": "New Note"
}

###
POST http://localhost:3001/api/data
Content-Type: application/json

{
  "important": "New Note"
}

###
POST http://localhost:3001/api/data
Content-Type: application/json

{
  "content": "Something",
  "important": false
}

###
DELETE http://localhost:3001/api/data/639c39619be1e9ae8fb07a23

###
GET http://localhost:3001/api/data/639c39619be1e9ae8fb07a23