POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "aceui",
  "name": "Alice Ceui",
  "password": "secret"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "New Blog",
  "author": "Alice",
  "url": "Blog url",
  "user": "63c4aced513b48c8daf29685"
}

###
GET http://localhost:3003/api/users

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "bobIsCool",
  "name": "Bob Cool",
  "password": "cool"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Bob's new house",
  "author": "Bob",
  "url": "Blog url",
  "user": "63c4adbe513b48c8daf29697"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Alice cooks food!",
  "author": "Alice",
  "url": "Blog url",
  "user": "63c4aced513b48c8daf29685"
}