GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes/63946077b2c77e16eba069e1

###
GET http://localhost:3001/somePath/

###
PUT http://localhost:3001/api/notes/63946077b2c77e16eba069e1
Content-Type: application/json

{
  "content": "HTML is Easy",
  "important": false
}

###
PUT http://localhost:3001/api/notes/63946077b2c77e16eba069e1
Content-Type: application/json

{
  "content": "HTML is Easy",
  "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "New Note to Add"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "New note to add",
  "important": true
}

###
GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/1

###
DELETE http://localhost:3001/api/notes/63a034ab941145485a3283ee

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "secretpassword"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "aceui",
  "name": "Alice Ceui",
  "password": "yay"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content":"User id of the note creator is at the start sent along the request",
  "important": true,
  "userId": "63a03e87f9c121bed155b07b"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "The existing code and tests need to be changed when users are added to the system",
  "important": true,
  "userId": "63a115a4e7c4afcd91d3fed5"
}